// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/index.qtpl:1
package templates

//line templates/index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/index.qtpl:2
type Index struct{}

//line templates/index.qtpl:5
func (p *Index) StreamTitle(qw422016 *qt422016.Writer) {
	//line templates/index.qtpl:5
	qw422016.N().S(`
  jojahner.de (tpl)
`)
//line templates/index.qtpl:7
}

//line templates/index.qtpl:7
func (p *Index) WriteTitle(qq422016 qtio422016.Writer) {
	//line templates/index.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/index.qtpl:7
	p.StreamTitle(qw422016)
	//line templates/index.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line templates/index.qtpl:7
}

//line templates/index.qtpl:7
func (p *Index) Title() string {
	//line templates/index.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/index.qtpl:7
	p.WriteTitle(qb422016)
	//line templates/index.qtpl:7
	qs422016 := string(qb422016.B)
	//line templates/index.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/index.qtpl:7
	return qs422016
//line templates/index.qtpl:7
}

//line templates/index.qtpl:9
func (p *Index) StreamBody(qw422016 *qt422016.Writer) {
	//line templates/index.qtpl:9
	qw422016.N().S(`
  <div>
    <h1>jojahner.de</h1>
  </div>
`)
//line templates/index.qtpl:13
}

//line templates/index.qtpl:13
func (p *Index) WriteBody(qq422016 qtio422016.Writer) {
	//line templates/index.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/index.qtpl:13
	p.StreamBody(qw422016)
	//line templates/index.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line templates/index.qtpl:13
}

//line templates/index.qtpl:13
func (p *Index) Body() string {
	//line templates/index.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/index.qtpl:13
	p.WriteBody(qb422016)
	//line templates/index.qtpl:13
	qs422016 := string(qb422016.B)
	//line templates/index.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/index.qtpl:13
	return qs422016
//line templates/index.qtpl:13
}
