// This file is automatically generated by qtc from "layout.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/layout.qtpl:1
package templates

//line templates/layout.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/layout.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/layout.qtpl:2
type Page interface {
	//line templates/layout.qtpl:2
	Title() string
	//line templates/layout.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
	//line templates/layout.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
	//line templates/layout.qtpl:2
	Body() string
	//line templates/layout.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
	//line templates/layout.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line templates/layout.qtpl:2
}

//line templates/layout.qtpl:8
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
	//line templates/layout.qtpl:8
	qw422016.N().S(`
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="author" content="jojahner">
    <meta name="description" content="personal homepage">
    <link rel="stylesheet" href="stylesheet.css" type="text/css">

    <title>`)
	//line templates/layout.qtpl:19
	p.StreamTitle(qw422016)
	//line templates/layout.qtpl:19
	qw422016.N().S(`</title>
  </head>
  <body>
    `)
	//line templates/layout.qtpl:22
	p.StreamBody(qw422016)
	//line templates/layout.qtpl:22
	qw422016.N().S(`
  </body>
</html>
`)
//line templates/layout.qtpl:25
}

//line templates/layout.qtpl:25
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
	//line templates/layout.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/layout.qtpl:25
	StreamPageTemplate(qw422016, p)
	//line templates/layout.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line templates/layout.qtpl:25
}

//line templates/layout.qtpl:25
func PageTemplate(p Page) string {
	//line templates/layout.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/layout.qtpl:25
	WritePageTemplate(qb422016, p)
	//line templates/layout.qtpl:25
	qs422016 := string(qb422016.B)
	//line templates/layout.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/layout.qtpl:25
	return qs422016
//line templates/layout.qtpl:25
}
